relyt4me/RefactorTractor-FitLit

.github/pull_request_template.md
Added our PR template to the hidden files and linked it
resolves #6
=> Create PR template and link

package-lock.json, src/User-repo.js, src/User.js, test/activity-test.js, test/sampleData/activitySampleData.js, test/sampleData/hydrationSampleData.js, test/sampleData/sleepSampleData.js, test/sampleData/userSampleData.js, test/user-test.js, test/userrepo-test.js
* Deep dive into the user and userRepo classes to find out what each of them is doing. 
* Clean up testing files for both
* Add sad paths and change to ES6 format
* Add `Math.Round()` to one of the methods in userRepo
* Add sample files for the testing
UserRepo.js or User.js
Still need to add sad paths to user-test file
resolves #11
=> Cc add notes to user/user repo

src/scripts.js
Adding comments to all of the methods and walking through the scripts.js file
changes all made to scipts.js
changes made that would affect fucntionality are just code order. Can be tested with a npm start and going to page
Walked through this together
resolves #18
=> Th reoder comment scriptsjs

src/Activity.js, test/activity-test.js
* Adds comments to each method in Activity class constructor
* Adds comments to some of test file for activity class
* Comment out unused methods in Activity class
* Use comments to designate section of tests to rewrite using more dynamics methods created later activity class
* Activity.js
* activity-test.js
* Just load the page and make sure it still works
resolves #12
=> Jms intitial code review

src/scripts.js
Going line by line moved all of the global documentbyID, Created a single function for the List HTML maker, renamed functions for better readability, Create global variables for only the repositories and variable used through multiple functions.
All changes made in scripts js follow from the startApp functions
page runs on npm start
Worked with this on call for clearer understanding between classes
comments in code represent changes and remove any that have been requested
resolves #14
=> Th refactor scripts

src/fetchAllData.js, test/sampleData/userSampleData.js, test/user-test.js
* Fixes last test of the user class testing file to make use of the sample data and return whats expected
* create file for the fetch data (still needs to be imported to scripts.js when we are ready)
fetchAllData.js
`npm test` for the user test file and user class 
fetch : n/a
resolves #19
=> Cc fetch file and test fix

src/User-repo.js, src/User.js, src/scripts.js, test/user-test.js, test/userrepo-test.js
* allows the method getFriendsName() in User class to work independently of userRepo
* adds sad paths to the user and UserRepo test suites
user.js, then testing files
`npm test`
=> Cc user rename

src/Activity.js, test/activity-test.js
* Initial refactor of activity class
* Gets rid of user-repo methods being used in methods that have nothing to do with user-repo
* Some refactoring of testing but still needs a major refactoring
* Activity.js
* activity-test.js
* npm test
* Check the website to make sure all is displaying
* The friends section of the class has not been touched
* The refactored and new methods should help quickly update the friends section
* The testing for activity still needs to be updated
* scripts file needs to be updated with edited or new methods
=> Jms activity class initial clean up

src/Sleep.js, src/scripts.js
* fix method that was returning users average sleep to be 5.48 out of 5. Changed method to divide by length of this.sleepData. It's working now.
* Link fetch file to scripts.js
scripts.js
open localhost:8080
resolves #31
=> Cc fetch all data

src/css/_main-section.scss, src/css/_mixins.scss, src/css/_user-card.scss, src/css/style.scss, src/index.html, src/scripts.js
* Begin renaming and restructuring the html layout
* implement sass and new files for breaking out sections of page for readability
`style.scss`
open up local host 
The main section isn't pulling any data until we get the styling looking good. All old html commented out.
=> Cc css html rework

src/Activity.js, test/activity-test.js, test/sampleData/activitySampleData.js
* All methods in activity class no long use user repo methods
* Fix bad calculations in week average methods using 8 days instead of 7
* Fix friends challenge winner methods to display actual winner rather than first in an unsorted list
* Activity.js
* activity-test.js
* npm test
* Just load the page and make sure it still works
=> Jms activity class friends refactor

src/Activity.js, test/activity-test.js, test/sampleData/activitySampleData.js
* Add more sad paths in activity class
* Activity and activity-test
* Just run npm test
=> Jms activity class sad paths

src/Hydration.js, src/Sleep.js, src/User-repo.js, src/index.html, src/scripts.js
* Update DOM with new method for the correct classes
* Delate all unneeded method inside of userRepo
scripts.js
Open local host 
The methods inside of other classes haven't been deleted yet but need to be cleaned up
resolves #42
=> Cc clean up user repo in scripts

src/DomUpdates.js, src/scripts.js, test/DomUpdates-test.js, test/sleep-test.js, test/userrepo-test.js
* Moves all DOM Updates into the DomUpdates class 
* start test file for the DOMUpdates, using spies
DomUpdates.js
npm test
resolves #25
=> Cc spies testing

src/postAllUserData.js
* creates framework of post all user data function
* postAllUserData.js
* There's no way to test the framework yet
* This may need to be broken down into 3 different functions depending on how we set up user inputs
Resolves #47
=> Create framework of posting all user data function

src/DomUpdates.js, src/Sleep.js, src/css/_main-section.scss, src/css/_right-side.scss, src/index.html, src/scripts.js, test/DomUpdates-test.js, test/sleep-test.js
Links the new User Interface to the scripts by changing scripts.js and DomUpdate
Change also made to Sleep for a dynamic averages checks
Scripts.js at the populate page portion.
Run npm start and watch the page load with current information
I was unable to get the last part of leaderboard to populate. Need to revisit the get winners for week functions in Sleep
resolves #53 
resolves #45  
resolves #26 
On line 91 of DomUpdate I am having trouble following the errors from this. I could use another set of eyes on it, Also some notes for checks with Jordy about activity.
=> Th link new html

src/Activity.js, src/DomUpdates.js, src/Sleep.js, test/activity-test.js
* Update some individual DOM displays
* Scripts.js
* Load the page and see what loads in the leaderboards section
=> Jms activity dom updates

src/DomUpdates.js, src/Sleep.js, src/index.html, src/scripts.js
* Changed method in sleep for fining the sleepiest user for any given day
* Sleep.js
=> Cc dom sleep challenge

src/DomUpdates.js, src/Sleep.js, src/index.html, src/scripts.js, test/DomUpdates-test.js
Completes the spies testing for getElementById used in the domUpdate portion. Minor changes made to sleep and scripts as cleanup while doing test.
Majority of changes to dom tests
run npm test
Spies testing for entire graph may be too much data in a test file.
resolves #55 
resolves #46 
resolves #44
=> Th spies documentid

src/css/_user-card.scss, src/index.html, src/scripts.js
* Creates functionality to pull information from user inputs when post button is clicked
* Constructs object to be posted
* The actual post function is commented out and needs to be uncommented later after testing
* lines 90 - 132 in scripts.js
* Insert information into user inputs, pull up console and see what is logged when post button is clicked
* #48 
* Should I create a separate file for this like we did with DomUpdates?
=> Jms post user input

src/Activity.js, test/activity-test.js
* Cleans up activity class and activity test
* Removes unused methods and tests
* Creates tests for untested methods
* Activity and activity-test files
* npm test activity-test
=> Jms activity cleanup

src/DomUpdates.js, src/Sleep.js, src/index.html
Ensures we utitlize the best sleep quality method, make sad path control for sleep averages incase of string and add quality of sleep to week information
changes made to Sleep.js, index.html and DomUpdates.js
Open browser after nmp start
resolves #66
=> Th week quality sleep

src/css/_mixins.scss, src/css/_variables.scss, src/css/style.scss
Add more color functions
sass files
resolves #63
=> Add color function and change coloring slightly

src/Activity.js, src/DomUpdates.js, src/index.html, src/scripts.js, test/activity-test.js
* Adds a 3 day streak date in the today at a glance for the 3 activities
* index.js
* DomUpdates
* scripts
* Load the page and inspect!
=> Jms display friends competition

src/DomUpdates.js, test/activity-test.js
* Corrects bad tests in activity-test
* Reorganizes DomUpdates file
* DomUpdates and activity-test
* npm test
* Open website and make sure all displays
=> Jms fetch bug fix

test/DomUpdates-test.js, test/activity-test.js
* Fixes failing tests in DomUpdates and Activity 
Testing files
npm test
resolves #80
=> Cc passing tests
